### ISSUE TITLE
Weird COLOR-RGB call

### ISSUE THREAD

**Issue by phoe** [tokenrove/imago#11]
https://github.com/tokenrove/imago/blob/9b01da5012c467322d6d4350a36b538ca39f1c42/operations.lisp#L197-L199

Is `color-rgb` meant to be there? Did you mean `color-red`?

**Comment by shamazmazum** [comment]
Oh thanks! Fixed.

**Comment by shamazmazum** [comment]
Note, that `color-rgb` returns red component as the first value, so it worked as intended, but I ment `color-red` for sure.

**Comment by phoe** [comment]
Yep, I guessed as much! A stroke of luck.
