### ISSUE TITLE
Is linear interpolation actually bilinear interpolation?

### ISSUE THREAD

**Issue by phoe** [tokenrove/imago#12]
https://github.com/tokenrove/imago/blob/9b01da5012c467322d6d4350a36b538ca39f1c42/operations.lisp#L181-L188

Since we're in 2D, I'd expect this kind of interpolation to be bilinear rather than just linear. Asking in context of nomenclature - if there is linear interpolation *and* bicubic interpolation present then there's some inconsistency that is best fixed early, before anyone uses this code.

**Comment by shamazmazum** [comment]
Sure, it's just a name. Fixed.
