### ISSUE TITLE
Architecture: add PIXEL-INTERPOLATOR

### ISSUE THREAD

**Issue by phoe** [tokenrove/imago#13]
From `#commonlisp` on Libera Chat:
```
18:10 < scymtym> i think it would make sense (in terms of performance) to have a generic function 
                 (pixel-interpolator image method) that returns a function x y -> pixel-value which 
                 closes over the results of WITH-IMAGE-DEFINITION and the type checks. the indirection 
                 through INTERPOLATE-PIXEL-CUBIC and interpreting the channel bits also seem like 
                 possible bottlenecks
```
I think that's a possible improvement for the future, once #10 is merged, since that would require changes to all interpolation schemes at once. What do you think?

**Comment by shamazmazum** [comment]
What's the difference between this method and `interpolate-pixel`?

**Comment by phoe** [comment]
Microoptimizations.

Currently in `interpolate-pixel-cubic` from #10, type checks for the `image` argument and resolving `width`, `height`, and `pixel` accessors happen on every call to `interpolate-pixel`; same stuff with `bytepositions` or `accessors` that I plan on refactoring them into. It'll be cheaper to get access to these values once and close over them instead of computing them every time.

Also, if `interpolate-pixel` is meant to be called tens of thousands of times for a medium-sized image, that's tens of thousands of GF call overheads that can be avoided this way.

**Comment by shamazmazum** [comment]
I added `interpolator` generic in place of `interpolate-pixel` and also removed recently added `width` and `height` slots from the `image` class.

I did it after profiling which says `array-dimension`/`array-dimensions` is very expensive to call it for every pixel in the image.

I noticed that `defpolymorph` exceeds the stack if a type specifier for the returned value is compound and the returned value is a function. Probabliy I should report this.

**Comment by shamazmazum** [comment]
Closing this

**Comment by phoe** [comment]
Thanks!

**Comment by phoe** [comment]
> if a type specifier for the returned value is compound and the returned value is a function

The [CLHS](http://clhs.lisp.se/Body/t_fn.htm) states:

> The list form of the function type-specifier can be used only for declaration and not for discrimination.

Maybe that's the reason? Do/can polymorphic functions support anything like that on their own?
