### ISSUE TITLE
type specifier

### ISSUE THREAD

**Issue by mdedwards** [tokenrove/imago#16]
Hello, I've been a happy user of imago on and off for a while now. Today I updated to the latest sbcl on osx 12.2, grabbed the latest quicklisp and now can't use imago any more because of the problem below.

Hoping it's a quick fix. Best, Michael

* is not permitted as an argument to the AND type specifier
   [Condition of type SIMPLE-ERROR]

Restarts:
 0: [RETRY] Retry compiling #<CL-SOURCE-FILE "imago" "interpolate">.
 1: [ACCEPT] Continue, treating compiling #<CL-SOURCE-FILE "imago" "interpolate"> as having been successful.
 2: [RETRY] Retry ASDF operation.
 3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the configuration.
 4: [RETRY] Retry ASDF operation.
 5: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the configuration.
 --more--

Backtrace:
  0: (SB-KERNEL:SPECIFIER-TYPE * #S(SB-KERNEL::TYPE-CONTEXT :SPEC (FUNCTION (# # # FUNCTION LIST) (AND * T)) :PROTO-CLASSOID NIL :OPTIONS 0) AND)
  1: (SB-KERNEL::PARSE-<AND> #S(SB-KERNEL::TYPE-CONTEXT :SPEC (FUNCTION (# # # FUNCTION LIST) (AND * T)) :PROTO-CLASSOID NIL :OPTIONS 0) (AND * T))
  2: (SB-KERNEL::%PARSE-TYPE (AND * T) #S(SB-KERNEL::TYPE-CONTEXT :SPEC (FUNCTION (# # # FUNCTION LIST) (AND * T)) :PROTO-CLASSOID NIL :OPTIONS 0))
  3: (SB-KERNEL::BASIC-PARSE-TYPESPEC (AND * T) #S(SB-KERNEL::TYPE-CONTEXT :SPEC (FUNCTION (# # # FUNCTION LIST) (AND * T)) :PROTO-CLASSOID NIL :OPTIONS 0))
  4: (SB-KERNEL::TRANSLATE-FUN-TYPE #S(SB-KERNEL::TYPE-CONTEXT :SPEC (FUNCTION (# # # FUNCTION LIST) (AND * T)) :PROTO-CLASSOID NIL :OPTIONS 0) ((ARRAY *) (SINGLE-FLOAT 0.0 1.0) (SINGLE-FLOAT 0.0 1.0) FUNC..
  5: (SB-KERNEL::%PARSE-TYPE (FUNCTION ((ARRAY *) (SINGLE-FLOAT 0.0 1.0) (SINGLE-FLOAT 0.0 1.0) FUNCTION LIST) (AND * T)) #S(SB-KERNEL::TYPE-CONTEXT :SPEC (FUNCTION (# # # FUNCTION LIST) (AND * T)) :PROTO-..
  6: (SB-KERNEL::BASIC-PARSE-TYPESPEC (FUNCTION ((ARRAY *) (SINGLE-FLOAT 0.0 1.0) (SINGLE-FLOAT 0.0 1.0) FUNCTION LIST) (AND * T)) #S(SB-KERNEL::TYPE-CONTEXT :SPEC (FUNCTION (# # # FUNCTION LIST) (AND * T)..
  7: (SB-KERNEL:SPECIFIER-TYPE (FUNCTION ((ARRAY *) (SINGLE-FLOAT 0.0 1.0) (SINGLE-FLOAT 0.0 1.0) FUNCTION LIST) (AND * T)) NIL NIL)
  8: (SB-C::%PROCLAIM (FTYPE (FUNCTION (# # # FUNCTION LIST) (AND * T)) POLYMORPHIC-FUNCTIONS.NONUSER::|(POLYMORPH INTERPOLATE-PIXEL-LINEAR ..)
  9: (PROCLAIM (FTYPE (FUNCTION (# # # FUNCTION LIST) (AND * T)) POLYMORPHIC-FUNCTIONS.NONUSER::|(POLYMORPH INTERPOLATE-PIXEL-LINEAR ..)
 10: ((LAMBDA NIL :IN "/Users/michael/quicklisp/dists/quicklisp/software/imago-20211230-git/interpolate.lisp"))
 11: (SB-INT:SIMPLE-EVAL-IN-LEXENV (LET NIL (SB-INT:DX-FLET NIL (SB-INT:DX-LET # #))) #<NULL-LEXENV>)
 12: (SB-INT:SIMPLE-EVAL-IN-LEXENV (PROGN (LET NIL (SB-INT:DX-FLET NIL #))) #<NULL-LEXENV>)
 13: (SB-EXT:EVAL-TLF (PROGN (LET NIL (SB-INT:DX-FLET NIL #))) 6 #<NULL-LEXENV>)
 14: ((FLET SB-C::FROB :IN SB-C::EVAL-COMPILE-TOPLEVEL))
 15: (SB-C::EVAL-COMPILE-TOPLEVEL ((LET NIL (SB-INT:DX-FLET NIL #))) ((LET NIL (SB-INT:DX-FLET NIL #)) (SB-KERNEL::%HANDLER-BIND #1=(#) (PROGN . #2=#)) #3=(HANDLER-BIND #1# . #2#) #4=(EVAL-WHEN #5=(:COMPIL..
 16: (SB-C::PROCESS-TOPLEVEL-FORM (LET NIL (SB-INT:DX-FLET NIL (SB-INT:DX-LET # #))) ((SB-KERNEL::%HANDLER-BIND #1=(#) (PROGN . #2=#)) #3=(HANDLER-BIND #1# . #2#) #4=(EVAL-WHEN #5=(:COMPILE-TOPLEVEL :LOAD-..
 17: (SB-C::PROCESS-TOPLEVEL-FORM (SB-KERNEL::%HANDLER-BIND ((WARNING #)) (PROGN (PROCLAIM #))) (#1=(HANDLER-BIND (#) (PROCLAIM #)) #2=(EVAL-WHEN #3=(:COMPILE-TOPLEVEL :LOAD-TOPLEVEL :EXECUTE) (SETF # #) #..
 18: (SB-C::PROCESS-TOPLEVEL-FORM (HANDLER-BIND ((WARNING #)) (PROCLAIM (QUOTE #))) (#1=(EVAL-WHEN #2=(:COMPILE-TOPLEVEL :LOAD-TOPLEVEL :EXECUTE) (SETF # #) (HANDLER-BIND # #) (POLYMORPHIC-FUNCTIONS::REGIS..
 19: (SB-C::PROCESS-TOPLEVEL-PROGN ((SETF (FDEFINITION #) (POLYMORPHIC-FUNCTIONS::LIST-NAMED-LAMBDA # #<PACKAGE "IMAGO"> # # # ...)) (HANDLER-BIND (#) (PROCLAIM #)) (POLYMORPHIC-FUNCTIONS::REGISTER-POLYMOR..

**Comment by shamazmazum** [comment]
Hi! Can you post the whole error message?

~~~~
is not permitted as an argument to the AND type specifier
[Condition of type SIMPLE-ERROR]
~~~~

seems truncated. Please post the message between lines `~~~~` like follows below, but without semicolons.
~~~~
;~~~~
dsds
;~~~~
~~~~

Also can you please specify the latest version of SBCL on osx 12.2? Do you mean 2.2.1?

**Comment by shamazmazum** [comment]
Oh, I see polymorphic-function in the backtrace. I tried it but managed to do stuff without it. I suspect your SBCL version is old, so please tell which one do you use?

**Comment by mdedwards** [comment]
Hi, thanks for the quick answer. Updated today to the latest sbcl via brew on osx: sbcl 2.1.9  I just checked that that is the latest available.

Funnily enough until then everything was working fine with sbcl 2.0.11 :/

Are you using functionality that changed so recently? Do you suggest building 2.2.1 from source? (What's your version?)

Best, Michael

**Comment by mdedwards** [comment]
PS I of course only got the latest imago src today so was working with older code in sbcl 2.0.11 -- that's probably why everything was fine

**Comment by shamazmazum** [comment]
Mine is 2.2.1.

Updating sbcl is an option. Another option is to use ultralisp:

~~~~
(ql-dist:install-dist "http://dist.ultralisp.org/"
                      :prompt nil)
(ql:quickload :imago)
~~~~

Ultralisp contains a newer version which should not cause any trouble on old SBCL.

> Updated today to the latest sbcl via brew on osx: sbcl 2.1.9

This version should be OK, isn't it?

**Comment by mdedwards** [comment]
Hi,

> Mine is 2.2.1.
> 
> Updating sbcl is an option. Another option is to use ultralisp:
> 
> (ql-dist:install-dist "http://dist.ultralisp.org/"
>                       :prompt nil)
> (ql:quickload :imago)
> 
> Ultralisp contains a newer version which should not cause any trouble on old SBCL.

Good to know but I think I’ll stick with SBCL for now.

> 
> Updated today to the latest sbcl via brew on osx: sbcl 2.1.9
> 
> This version should be OK, isn't it?

No that’s the one where I first saw the problem :/

To be honest I’ve never been a great fan of quicklisp and here once again it caused more problems than it’s solved :/ I’ve simply rolled back my version of imago and now load the system with asdf alone. It’s now fine again.

Thanks for your help though!

Cheers, michael

**Comment by shamazmazum** [comment]
> Good to know but I think I’ll stick with SBCL for now.

Ultralisp is not an implementation of Common Lisp, it's a quickly updating package distribution. It will work with any (or almost any implementation): SBCL, CMUCL, ABCL, clisp, lispworks, etc. So you can use Ultralisp with SBCL freely.

> To be honest I’ve never been a great fan of quicklisp and here once again it caused more problems than it’s solved

Strange to hear that :)

You can give Ultralisp a try and check if imago works fine (I think it should). Also you can close an issue if your problem is solved.

BTW, you can install older versions of software with quicklisp if you wish.

**Comment by mdedwards** [comment]
Ah, good to know about ultralisp: I’m so not a netscourer of all things lisp :) Will take a look. Thanks again, best, Michael
