### ISSUE TITLE
Missing example how to create a new image (not load it from somewhere)

### ISSUE THREAD

**Issue by ruffianeo** [tokenrove/imago#5]
Maybe I just did not look into how CLOS works - but I could not find a way to create an image, which I can then use to render to.
So an example would be nice.

**Comment by tokenrove** [comment]
`(make-instance 'rgb-image :width width :height height)` I believe.

Feel free to add examples to the README.

**Comment by ruffianeo** [comment]
```
(defvar *image*)

(defun new-image (width height)
  (imago::make-instance 'imago::rgb-image
                        :width width
                        :height height))

(defmacro with-new-image (width height &body body)
  `(let ((w ,width)
         (h ,height)
         (*image* (new-image ,width ,height)))
     (declare (ignorable w h))
     ,@body
     *image*))
```
Documentation still needed, for example: Is there also an `'imago::rgba-image` image type?
And something should be exported (made public), so people can just find it without looking at internals.

**Comment by shamazmazum** [comment]
You are right. I'll write some documented constructors soon.

**Comment by shamazmazum** [comment]
@ruffianeo I added type-annotated constructors like `make-grayscale-image`, `make-grayscale-image-from-pixels` and so on. While there I added type annotations and optimization declarations for color constructors/accessors, things must be faster now (not measured). Readme is updated accordingly.

Sorry for the documentation not being perfect.

**Comment by shamazmazum** [comment]
@ruffianeo Closing this issue. If you have something to add, feel free to reopen.
