### ISSUE TITLE
Add histogram equalization

### ISSUE THREAD

**Issue by Lautaro-Garcia** [tokenrove/imago#6]
Hello!

I've been using this library for a project lately and I had to implement [a general histogram equalization algorithm](https://en.wikipedia.org/wiki/Histogram_equalization) for adjusting the contrast of a grayscale image. I thought it might be useful to someone else, and it could be a good idea to add it to the library (as the `blur` or `sharpen` functions, but not based on the `convolve` function). My implementation is for grayscale images only and I think is the simplest kind of equalization (I'm no expert on the field or whatsoever).

Do you think is a good idea to add this?

**Comment by shamazmazum** [comment]
Sure, even if it works only for grayscale images, you can write a method only for `imago:grayscale-image`:
~~~~
(defmethod histogram-equalization ((image grayscale-image))
    .....)
~~~~

Please send a pull request and I will merge it into imago.

**Comment by Lautaro-Garcia** [comment]
Thank you! I'm going to close this issue now, the PR has been merged already
